### ISSUE TITLE
Builds hanging in CircleStylePlugin after upgrading to 1.1.0

### ISSUE THREAD

**Issue by dtobin** [palantir/gradle-circle-style#3]
Looks like the File.exists call is hanging, maybe an issue with the filesystem?

Stacktrace of the gradle daemon:
```
"Daemon worker" #29 prio=5 os_prio=0 tid=0x00007efd5c00a800 nid=0x2d11 runnable [0x00007efd72342000]
   java.lang.Thread.State: RUNNABLE
        at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
        at java.io.File.exists(File.java:819)
        at com.palantir.gradle.circlestyle.CircleStylePlugin.configureBuildFailureFinalizer(CircleStylePlugin.java:67)
        at com.palantir.gradle.circlestyle.CircleStylePlugin.apply(CircleStylePlugin.java:40)
        at com.palantir.gradle.circlestyle.CircleStylePlugin.apply(CircleStylePlugin.java:31)
```

**Comment by j-baker** [comment]
Yeah have seen this too

**Comment by dtobin** [comment]
Oh nvm, it's a simple bug: https://github.com/palantir/gradle-circle-style/blob/master/src/main/java/com/palantir/gradle/circlestyle/CircleStylePlugin.java#L68

**Comment by alicederyn** [comment]
I've found the bug too. Thanks, that stack trace was awesome.
