### ISSUE TITLE
Not set: [file, line]

### ISSUE THREAD

**Issue by alicederyn** [palantir/gradle-circle-style#7]
Some FindBugs errors cause gradle-circle-style to fail:

```
java.lang.IllegalStateException: Not set: [file, line]
	at com.palantir.gradle.circlestyle.Failure_Builder.build(Failure_Builder.java:249)
	at com.palantir.gradle.circlestyle.Failure$Builder.build(Failure.java:31)
	at com.palantir.gradle.circlestyle.FindBugsReportHandler.endElement(FindBugsReportHandler.java:111)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.palantir.gradle.circlestyle.FindBugsReportHandler$1.loadFailures(FindBugsReportHandler.java:42)
	at com.palantir.gradle.circlestyle.CircleStyleFinalizer.createCircleReport(CircleStyleFinalizer.java:100)
```

**Comment by alicederyn** [comment]
This seems to be due to my mistaken assumption that `primary` would always be set to `true` on the top-level SourceLine element of each BugInstance. Should be an easy fix.
